# Generated by Django 3.2.9 on 2021-11-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=30)),
                ('DNI', models.IntegerField(max_length=8)),
            ],
        ),
    ]
