# Generated by Django 3.2.9 on 2021-11-23 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
